### ISSUE TITLE
[BUG] Error loading bcrypt shared library

### ISSUE THREAD

**Issue by alvarobernal2412** [FIS2425/authorization-svc#67] opened 2024-11-17 21:59 UTC
## Description

When attempting to use bcrypt in a Docker container on macOS, an error occurs while loading the bcrypt shared library. The error message indicates that there is an "Exec format error" when trying to load the `bcrypt_lib.node` file.

## Steps to Reproduce

1. Set up a Docker container running a Node.js application on macOS.
2. Install `bcrypt` via npm (or yarn).
3. Attempt to run the application that uses `bcrypt`.

## Expected Behavior

The bcrypt library should load and function correctly without any errors.

## Actual Behavior

An `ERR_DLOPEN_FAILED` error is thrown, indicating that the shared library for bcrypt could not be loaded due to an "Exec format error." This prevents the application from using bcrypt.

## Context

- OS: macOS Sequoia 15.0.1
- Node.js Version: 22.11.0
- Docker Version:  24.0.6
- Architecture: arm64

**Comment by AntonioRodriguezRuiz** [comment] 2024-11-17 22:02
Sorry I can't reproduce but will believe you.

Will fix

**Comment by AntonioRodriguezRuiz** [comment] 2024-11-18 15:45
Will be fixed by removing the volume

**Closed** 2024-11-18 17:10 UTC
Labels: 🐞 Bug
